---
title: "Network analysis"
author: "Diego Villa, Diego Salcedo"
date: '2022-03-04'
output:
  html_document:
    df_print: paged
---

```{r}
library(fs)
library(dplyr)
library(readr)
library(tidyr)
library(tidygraph)
library(ggraph)
library(igraph)
library(GGally)
library(ggplot2)
```

```{r}
processed_path <- fs::path("data", "processed")
nodes_filename <- "nodes.csv"
nodes_filepath <- fs::path(processed_path, nodes_filename)
nodes <- read_csv(nodes_filepath, col_types = "cccc")
glimpse(nodes)
```

```{r}
raw_path <- fs::path("data", "processed")
edges_filename <- "edges.csv"
edges_filepath <- fs::path(processed_path, edges_filename)
edges <- read_csv(edges_filepath, col_types = "ccd")
glimpse(edges)
```

# Network creation

```{r}
mob_tb_graph <-
  tbl_graph(nodes = nodes, edges = edges, directed = TRUE)
```

# Network overall characteristics

```{r}
n_nodes <- gorder(mob_tb_graph)
n_nodes
```

```{r}
n_edges <- gsize(mob_tb_graph)
n_edges
```

```{r}
edge_density(mob_tb_graph) # conexiones en la data / todas las posibles conexiones 
```

# Centrality

```{r}
# It is possible to specify our own score with centrality_manual 

mob_tb_centralities <- mob_tb_graph %>%
  activate(nodes) %>%
  mutate(
    in_degree = centrality_degree(mode = "in") / (n_nodes - 1),
    out_degree = centrality_degree(mode = "out") / (n_nodes - 1),
    in_strength = centrality_degree(weights = weight, mode = "in"),
    out_strength = centrality_degree(weights = weight, mode = "out"),
    in_closeness = centrality_closeness(weights = weight, mode = "in"),
    out_closeness = centrality_closeness(weights = weight, mode = "out"),
    closeness = centrality_closeness(weights = weight, mode = "all"),
    betweenness = centrality_betweenness(weights = weight, normalized = TRUE),
    # eigenvector = centrality_eigen(weights = weight, directed = TRUE), #   PageRank may be better for directed graphs
    # https://lists.nongnu.org/archive/html/igraph-help/2015-11/msg00020.html
    page_rank = centrality_pagerank(weights = weight),
    alpha = centrality_alpha(weights = weight), # Don't know how to define alpha yet
    authority = centrality_authority(weights = weight),
    hub = centrality_hub(weights = weight)
  ) %>% 
  activate(nodes) %>% 
  as_tibble()
```

```{r}
glimpse(mob_tb_centralities)
```

```{r}
mob_tb_filename <- "mob-tb.csv"
mob_tb_filepath <- fs::path(processed_path, mob_tb_filename)
write_csv(mob_tb_centralities, mob_tb_filepath, na = "")
```

```{r}
variable <- colnames(mob_tb_centralities)
description <- rep(NA, length(variable))
dict <- tibble(variable, description)
dict_filepath <- fs::path(processed_path, "data-dictionary.csv")
write_csv(dict, dict_filepath, na = "")
```

```{r}
mob_lima %>% 
  ggplot(aes(in_degree)) +
  geom_histogram(bins = 15)
```

```{r}
mob_lima %>% 
  ggplot(aes(out_degree)) +
  geom_histogram(bins = 15)
```

```{r}
mob_lima %>% 
  ggplot(aes(in_strength)) +
  geom_histogram(bins = 15)
```

```{r}
mob_lima %>% 
  ggplot(aes(in_degree, in_strength)) +
  geom_point()
```


# TB cases

```{r}
tb_file_name <- "tb-cases-lima-2017.csv"
tb_file_path <- fs::path(raw_path, tb_file_name)
tb_lima_raw <- read_csv(tb_file_path)
glimpse(tb_lima_raw)
```

```{r}
tb_lima_raw %>% 
  filter(YEAR == 2017) %>% 
  select(
    ubigeo_eess, new_cases = casos_nuevos, 
    max_temperature:delta_temperature
  ) %>% 
  mutate(ubigeo_eess = as.character(ubigeo_eess)) ->
  tb_lima
```

```{r}
tb_lima %>% 
  inner_join(mob_lima, by = c("ubigeo_eess" = "ubigeo")) %>% 
  select(ubigeo = ubigeo_eess, population, new_cases, everything()) ->
  mob_tb_lima
```

```{r}
mob_tb_lima
```

```{r}
# demo_filename <- "demographics.csv" 
# demo_path <- fs::path(raw_path, demo_filename)
demo_raw <- read_csv("data/processed/demographics.csv", col_types = paste(c(rep("c", 4), rep("d", 13))))
```

```{r}
demo <- demo_raw %>% 
  select(-one_of(c("department", "province", "district")))
```


```{r}
mob_tb <- mob_tb_lima %>% 
  select(-population) %>% 
  select(-one_of(c("department", "province", "district"))) %>% 
  left_join(demo, by = "ubigeo")
```

```{r}
mob_tb
```


```{r}
# out_file_name <- "mob-tb-lima-2017.csv"
# out_file_path <- fs::path(interim_path, out_file_name)
write_csv(mob_tb_lima, "data/processed/mob-tb-lima-2017.csv")
```

# Exploratory data analysis

```{r}
mob_tb_lima %>% 
  select(in_degree:hub) %>% 
  ggpairs()
```

```{r}
mob_tb_lima %>% 
  mutate(incidence = 100000 * casos_nuevos / poblacion) %>% 
  select(incidencia, incidence)
```

```{r}
mob_tb_lima %>% 
  mutate(morbility = 100000 * total_casos / poblacion) %>% 
  select(morbilidad, morbility)
```

